// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: services/meta/proto/meta_service.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllSystemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllSystemsRequest) Reset() {
	*x = GetAllSystemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_meta_proto_meta_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllSystemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSystemsRequest) ProtoMessage() {}

func (x *GetAllSystemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_meta_proto_meta_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSystemsRequest.ProtoReflect.Descriptor instead.
func (*GetAllSystemsRequest) Descriptor() ([]byte, []int) {
	return file_services_meta_proto_meta_service_proto_rawDescGZIP(), []int{0}
}

type GetAllSystemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Systems []*System `protobuf:"bytes,1,rep,name=systems,proto3" json:"systems,omitempty"`
}

func (x *GetAllSystemsResponse) Reset() {
	*x = GetAllSystemsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_meta_proto_meta_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllSystemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSystemsResponse) ProtoMessage() {}

func (x *GetAllSystemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_meta_proto_meta_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSystemsResponse.ProtoReflect.Descriptor instead.
func (*GetAllSystemsResponse) Descriptor() ([]byte, []int) {
	return file_services_meta_proto_meta_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllSystemsResponse) GetSystems() []*System {
	if x != nil {
		return x.Systems
	}
	return nil
}

type System struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SystemNo        int64  `protobuf:"varint,1,opt,name=system_no,json=systemNo,proto3" json:"system_no,omitempty"`
	SystemName      string `protobuf:"bytes,2,opt,name=system_name,json=systemName,proto3" json:"system_name,omitempty"`
	SystemShortName string `protobuf:"bytes,3,opt,name=system_short_name,json=systemShortName,proto3" json:"system_short_name,omitempty"`
	SetUser         string `protobuf:"bytes,4,opt,name=set_user,json=setUser,proto3" json:"set_user,omitempty"`
	SetTimestamp    string `protobuf:"bytes,5,opt,name=set_timestamp,json=setTimestamp,proto3" json:"set_timestamp,omitempty"`
}

func (x *System) Reset() {
	*x = System{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_meta_proto_meta_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *System) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*System) ProtoMessage() {}

func (x *System) ProtoReflect() protoreflect.Message {
	mi := &file_services_meta_proto_meta_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use System.ProtoReflect.Descriptor instead.
func (*System) Descriptor() ([]byte, []int) {
	return file_services_meta_proto_meta_service_proto_rawDescGZIP(), []int{2}
}

func (x *System) GetSystemNo() int64 {
	if x != nil {
		return x.SystemNo
	}
	return 0
}

func (x *System) GetSystemName() string {
	if x != nil {
		return x.SystemName
	}
	return ""
}

func (x *System) GetSystemShortName() string {
	if x != nil {
		return x.SystemShortName
	}
	return ""
}

func (x *System) GetSetUser() string {
	if x != nil {
		return x.SetUser
	}
	return ""
}

func (x *System) GetSetTimestamp() string {
	if x != nil {
		return x.SetTimestamp
	}
	return ""
}

var File_services_meta_proto_meta_service_proto protoreflect.FileDescriptor

var file_services_meta_proto_meta_service_proto_rawDesc = []byte{
	0x0a, 0x26, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x16, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x4e, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x07,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x73, 0x22, 0xb2, 0x01, 0x0a, 0x06, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x11,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x32, 0x8c, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x74,
	0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x7d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x29, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x73, 0x42, 0x42, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x61, 0x6e, 0x43, 0x61, 0x6c, 0x65, 0x62, 0x4d, 0x61,
	0x6e, 0x7a, 0x61, 0x6e, 0x6f, 0x2f, 0x74, 0x61, 0x67, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_services_meta_proto_meta_service_proto_rawDescOnce sync.Once
	file_services_meta_proto_meta_service_proto_rawDescData = file_services_meta_proto_meta_service_proto_rawDesc
)

func file_services_meta_proto_meta_service_proto_rawDescGZIP() []byte {
	file_services_meta_proto_meta_service_proto_rawDescOnce.Do(func() {
		file_services_meta_proto_meta_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_meta_proto_meta_service_proto_rawDescData)
	})
	return file_services_meta_proto_meta_service_proto_rawDescData
}

var file_services_meta_proto_meta_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_meta_proto_meta_service_proto_goTypes = []interface{}{
	(*GetAllSystemsRequest)(nil),  // 0: services.meta.proto.GetAllSystemsRequest
	(*GetAllSystemsResponse)(nil), // 1: services.meta.proto.GetAllSystemsResponse
	(*System)(nil),                // 2: services.meta.proto.System
}
var file_services_meta_proto_meta_service_proto_depIdxs = []int32{
	2, // 0: services.meta.proto.GetAllSystemsResponse.systems:type_name -> services.meta.proto.System
	0, // 1: services.meta.proto.MetaService.GetAllSystems:input_type -> services.meta.proto.GetAllSystemsRequest
	1, // 2: services.meta.proto.MetaService.GetAllSystems:output_type -> services.meta.proto.GetAllSystemsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_meta_proto_meta_service_proto_init() }
func file_services_meta_proto_meta_service_proto_init() {
	if File_services_meta_proto_meta_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_meta_proto_meta_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllSystemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_meta_proto_meta_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllSystemsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_meta_proto_meta_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*System); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_meta_proto_meta_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_meta_proto_meta_service_proto_goTypes,
		DependencyIndexes: file_services_meta_proto_meta_service_proto_depIdxs,
		MessageInfos:      file_services_meta_proto_meta_service_proto_msgTypes,
	}.Build()
	File_services_meta_proto_meta_service_proto = out.File
	file_services_meta_proto_meta_service_proto_rawDesc = nil
	file_services_meta_proto_meta_service_proto_goTypes = nil
	file_services_meta_proto_meta_service_proto_depIdxs = nil
}
